apiVersion: v2
name: my-homelab-setup
description: A Helm chart for deploying my complete homelab setup.
version: 0.1.0
appVersion: "1.0"
dependencies:
  # Example for Argo CD
  - name: argo-cd
    version: 3.35.4
    repository: https://argoproj.github.io/argo-helm

  - name: longhorn
    version: 1.8.1
    repository: https://charts.longhorn.io

  - name: metallb
    version: 0.14.9
    repository: https://metallb.github.io/metallb/

  - name: pihole
    version: 2.29.1
    repository: https://mojo2600.github.io/pihole-kubernetes/

  - name: traefik
    version: 35.0.1
    repository: https://traefik.github.io/charts

  - name: cert-manager
    version: v1.17.1
    repository: https://charts.jetstack.io/

  - name: nextcloud
    version: 6.6.10
    repository: https://nextcloud.github.io/helm/
