apiVersion: v1
data:
  config.yaml: |
    tunnel: credentials_id #in the filename of the output of cloudflared create tunnel
    credentials-file: ~/credentials.json #output of cloudflared create tunnel

    ingress:
      - hostname: "*.mydomain.com"
        service: http://traefik.kube-system:80
      - service: http_status:404
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflare