apiVersion: v1
kind: Service
metadata:
  name: pihole
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.241
spec:
  selector:
    app: pihole
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 80
    - name: dns-tcp
      port: {{ .Values.service.dnsTCPPort }}
      targetPort: 53
      protocol: TCP
    - name: dns-udp
      port: {{ .Values.service.dnsUDPPort }}
      targetPort: 53
      protocol: UDP
